### ISSUE TITLE
1. 서비스 기획

### ISSUE THREAD

**Issue by f-lab-robert** [f-lab-edu/retry-lee#1]
**[Context]**
1. API 서버
2. 호텔 예약 시스템
- Admin
  - 호텔을 등록, 수정, 삭제

- User 
  - 호텔 예약, 취소, 수정
  - 로그인, 회원가입

**Comment by sypatrick** [comment]
기획 화면

[Book&Stay](https://ovenapp.io/project/UurTNK8DcF3RMtGxz86NesfgUJB4QXZi#gyM6U)

1. 메인화면
2. 로그인
3. 회원가입
4. 마이페이지 (일반회원 / 관리자)
5. 예약 상세보기
&ensp; - 수정, 취소 신청
&ensp; - 수정시 체크인 날짜, 이름, 인원 변경 가능
6. 신규 숙소 등록
7. 예약화면 - 1
8. 예약화면 - 2
9. 질문 게시판
10. 게시글 화면
