### ISSUE TITLE
[Test] Unit. E2E 테스트 분리

### ISSUE THREAD

**Issue by f-lab-robert** [f-lab-edu/retry-lee#11]
**[Context]**
- Unit 테스트 
- E2E 테스트 ( testContainer )
- 2개의 테스트를 분리 ./gradlew unitTest 의 경우 unit test 만 실행, ./gradlew e2eTest 의 경우 e2e test 만 실행

**Comment by sypatrick** [comment]
_각 장단점을 기술하는 기준은 구현 복잡도, 유지보수성, IDE지원으로 정하고 추가 사항은 기타로 정리하였습니다._

### 1. Junit 에 @Tag를 사용하는 방법
```
@Tag("unit")
public class UserServiceTest {
    
    @Test
    void testCreateUser() {
        // Unit 테스트 로직
    }
}

@Tag("e2e")
public class UserServiceE2ETest {
    
    @Test
    void testUserCreationFlow() {
        // E2E 테스트 로직
    }
}
```

- 장점
  - 구현 복잡도 : 클래스당 한번의 @Tag만 추가하면 되어 구현이 간단하다.
  - 유지보수성 : 테스트 유형별로 클래스를 명확히 구분하여 관리가능하다.
  - IDE 지원 : 대부분의 IDE에서 지원한다.
  - 기타 : Gradle 이나 Maven을 통해 특정 태그의 테스트만 실행할 수 있다.

- 단점
  - 구현 복잡도 : 테스트 케이스가 많아질 경우 일일히 Tag 작업을 확인해야 한다.
  - 유지보수성 : 태그 관리가 제대로 되지 않으면 불필요한 태그가 누적될 수 있다.
  - 기타 : 통합테스트와 단위테스트 각각의 라이브러리 의존성 설정이 복잡해 질 수 있다.

***

### 2. Gradle의 source set 기능을 활용한 분리 방법

```
sourceSets {
    e2eTest {
        java {
            compileClasspath += main.output + test.output
            runtimeClasspath += main.output + test.output
            srcDir file('src/e2eTest/java')
        }
        resources.srcDir file('src/e2eTest/resources')
    }
}
```

#### _main.out, test.output_

- main.output과 test.output은 각각 main 소스 세트와 test 소스 세트의 컴파일된 클래스 파일들을 나타낸다.

- main.output:
  - src/main/java 디렉토리의 소스 코드가 컴파일된 결과물을 가리킨다.
  - 주로 build/classes/java/main 디렉토리에 위치.
  - 프로젝트의 주요 소스 코드의 컴파일된 클래스 파일들을 포함한다.

- test.output:
  - src/test/java 디렉토리의 테스트 소스 코드가 컴파일된 결과물을 가리킨다.
  - 주로 build/classes/java/test 디렉토리에 위치.
  - 단위 테스트의 컴파일된 클래스 파일들을 포함합니다.

위의 예제에서 e2eTest 소스 세트를 설정할 때 main.output과 test.output을 클래스패스에 추가하는 이유

main.output 추가: E2E 테스트가 프로젝트의 주요 코드를 참조할 수 있게 한다.
예를 들어, E2E 테스트에서 애플리케이션의 주요 클래스나 인터페이스를 사용할 수 있다.

test.output 추가: E2E 테스트가 단위 테스트에서 정의한 유틸리티 클래스나 메소드를 재사용할 수 있게 된다.
테스트 간의 코드 중복을 줄이고 일관성을 유지하는 데 도움이 된다.


- 장점
  - 구현 복잡도 : Gradle 설정만으로 단위 테스트와 통합테스트 분리가 가능하다.
  - 유지보수성 : 각 테스트의 소스코드와 리소스가 완전히 분리되어 관리하기 수월하다.
  - IDE 지원 : 대부분의 IDE에서 지원한다.(각 테스트를 별도의 모듈처럼 인식)
  - 기타 : 각 테스트의 추가적인 의존성 관리가 보다 편해진다.

- 단점
  - 구현 복잡도 : 초기 Gradle 설정이 다소 복잡하여 학습비용이 추가된다.
  - 유지보수성 : 테스트 코드가 물리적으로 분리되어 있어 공통 로직에 대한 중복이 발생할 수 있어 관리에 주의해야 한다.

***

### 3. Gradle의 JVM Test Suite 

- Gradle 7.3부터 도입된 새로운 테스트 관리 기능으로, 여러 테스트 세트를 쉽게 정의할 수 있게 도와준다.

```
suites {
        // 단위 테스트 스위트
        unitTest(JvmTestSuite) {
            useJUnitJupiter()
            dependencies {
                // 단위 테스트에 필요한 추가 의존성
            }
        }
        // E2E 테스트 스위트
        e2eTest(JvmTestSuite) {
            useJUnitJupiter()
            dependencies {
                // E2E 테스트에 필요한 추가 의존성
            }
            sources {
                java {
                    srcDir 'src/e2eTest/java'
                }
                resources {
                    srcDir 'src/e2eTest/resources'
                }
            }
            targets {
                all {
                    testTask.configure {
                        systemProperty 'spring.profiles.active', 'e2e'
                        // E2E 테스트를 위한 추가 설정
                    }
                }
            }
        }
```

- 장점
  - 구현 복잡도 : 스위트 정의가 직관적이고 명확하다
  - 유지보수성 : 각 테스트 유형별로 스위트를 명확하게 분리하여 관리하기 좋고, 의존성을 독립적으로 관리 가능하다.
  - 기타 : 테스트 실행 순서 및 설정을 세밀하게 조정 가능하다.

- 단점
  - 구현 복잡도 : 초기 Gradle 설정이 다소 복잡하고 Gradle 7.3버전 이상이 필요하다.
  - 유지보수성 : source set으로 구분하는 것과 같이 테스트 스위트가 많아질 경우 gradle 설정이 복잡해진다.

***

### 통합테스트 라이브러리 

#### 1. TestRestTemplete
- 장점
  - 스프링 부트에 기본으로 포함되어 있어 별도 설정없이 사용가능.
  - RestTemplete과 유사한 API 제공하여 RestAssured 보다 쉽게 사용가능 (학습 비용이 적다)
- 단점
  - 복잡한 요청을 구성할 때 RestAssured 보다 코드가 길어질 수 있다.
  - AssertJ 등의 라이브러리를 함께 써야 상세한 응답 검증이 가능하다.

```
ResponseEntity<List<User>> response = restTemplate.exchange(
    "/api/users", HttpMethod.GET, null, 
    new ParameterizedTypeReference<List<User>>() {}
);
assertThat(response.getStatusCode()).isEqualTo(HttpStatus.OK);
assertThat(response.getBody()).hasSizeGreaterThan(0);
assertThat(response.getBody().stream().filter(u -> u.getAge() > 18).count()).isGreaterThan(5);
assertThat(response.getBody().get(0).getAddress().getCity()).isEqualTo("Seoul");
```
***
#### 2. RestAssured
 - 장점
   - Given-When-Then 구조의 DSL 이 제공된다.
   - 복잡한 요청을 간단하게 설정할 수 있다.
 - 단점
   - 별도 의존성 추가가 필요하다.
   - @SpringBootTest 와 함께 사용할 때 약간의 추가 설정이 필요하다.
```
given()
    .port(port)
.when()
    .get("/api/users")
.then()
    .statusCode(200)
    .body("size()", greaterThan(0))
    .body("findAll { it.age > 18 }.size()", greaterThan(5))
    .body("[0].address.city", equalTo("Seoul"));
```
***
#### 결론

TestRestTemplete이 스프링부트에서 기본으로 제공하며, Spring을 이용하던 개발자면 쉽게 사용할 수 있다는 점에서 선택했습니다.
물론 RestAssured 도 조금만 학습하면 좋은 대안이 될 수 있지만, 통합테스트를 학습하는 입장에서 SpringBoot의 포함되어 있는 것 부터 알아가야한다고 생각해서 선택했습니다.
이 외에 Cucumber, WebTestClient 등이 있는데, Cucumber는 RestAssured와 선택하지 않은 이유가 같고, WebTestClient는 Spring Webflux에서 많이 사용하며 비동기 특성을 가진 테스트를 작성할 때 적합하다고 생각해 배제했습니다.
