### ISSUE TITLE
[System 설계] Diagram

### ISSUE THREAD

**Issue by f-lab-robert** [f-lab-edu/retry-lee#22]
**[Context]**
- Route53 with ACM, Application LoadBalancer, ECR, ECS, (default) VPC/subnet 를 이용해서 실제로 승용님이 직접 만들 서비스 아키텍처를 Diagram 으로 그려오기

**Comment by f-lab-robert** [comment]
[사용자 입장]

- https://..... 를 enter -> springBoot 의 backend api 가 호출되어야한다.

**Comment by sypatrick** [comment]
![image](https://github.com/user-attachments/assets/ec669bd2-7351-4f71-ae2f-6c1800396225)

***

### Route 53
- 미리 구매한 도메인을 등록하거나 Route53에서 도메인 구매 후 등록
- Frontend : retrylee.com
- Backend : api.retrylee.com

> 도매인 구매는 가비아, 후이즈 등의 기업에서 구매할 수 있고  .com, .co.kr 등등 도메인에 따라 가격이 달라진다.

**Comment by sypatrick** [comment]
## Route 53
- 개념 : Route 53은 Amazon Web Services(AWS)에서 제공하는 확장 가능한 도메인 네임 시스템(DNS) 웹 서비스
- 호스팅 영역(Hosted Zone)
  - 도메인과 그 하위 도메인의 트래픽을 라우팅하는 방법을 정의하는 컨테이너
  - 각 호스팅 영역에는 도메인에 대한 레코드 세트가 포함
- 레코드
  - 도메인 네임 시스템에서 특정 도메인에 대한 정보를 저장하는 데이터 항목
- 레코드 세트
  - 특정 도메인이나 하위 도메인에 대한 트래픽을 어떻게 처리할지 정의
- 라우팅 정책
  - 단순 라우팅: 기본적인 DNS 라우팅
  - 가중치 기반 라우팅: 트래픽을 여러 리소스로 분산
  - 지연 시간 기반 라우팅: 사용자에게 가장 가까운 리소스로 라우팅
  - 지리적 위치 라우팅: 사용자의 지리적 위치에 따라 라우팅
  - 장애 조치 라우팅: 주 리소스에 문제 발생 시 백업으로 전환
- 도메인 등록
  - 새로운 도메인을 등록하고 관리

## ACM(Amazon Certificate Manager)
- 개념 : ACM은 AWS에서 제공하는 서비스로, SSL/TLS 인증서의 프로비저닝, 관리, 배포를 쉽게 처리할 수 있게 해주는 서비스. 웹사이트나 애플리케이션의 보안을 강화하고 HTTPS 연결을 용이하게 구현할 수 있다.

**Comment by sypatrick** [comment]
![image](https://github.com/user-attachments/assets/ec669bd2-7351-4f71-ae2f-6c1800396225)

***
_위 그림을 그려보면서 혹은 그려보고 나서 생각해봤던 것들에 대한 정리입니다._

### 1. Route 53, LoadBalancer
- 미리 구매한 도메인을 등록하거나 Route53에서 도메인 구매 후 등록한다.
  - Frontend : retrylee.com
  - Backend : api.retrylee.com

> 도매인 구매는 가비아, 후이즈 등의 기업에서 구매할 수 있고  .com, .co.kr 등등 도메인에 따라 가격이 달라진다.

- Frontend, Backend 각각의 도메인으로 들어온 요청에 대하여 로드밸런서에 의해 서비스로 요청이 이루어진다.

### 2. CORS
- 같은 서브넷에 프론트엔드, 백엔드 서비스가 각각 있더라도 CORS 설정을 해주어야 한다. 백엔드에서 직접 해주거나, Gateway를 두어 해결할 수 있다.

### 3. Http, Https
- ACM 을 이용하여 인증서를 등록하고 https로 요청을 하면 인증정보 확인후 연결할 수 있는데, http로 들어올 경우 처리 방법들
1. 프론트에서 직접 리다이렉트 설정
    - 너무 단순한 방법이기도 하고 생각해보면 프론트로 접근을 한번 했다는 거 자체가 좋은 방법일 수 없다.
2. 로드밸런서에서 설정
    - AWS의 ALB의 경우 http(80)로 들어온 요청에 대하여 https(443)으로 301코드와 함께 리디렉션할 수 있는 기능이 제공.

- ACM 을 사용하지 않고 ALB도 사용하지 않는다면..
  - Cafe24등의 SSL 인증서 발급기관에서 SSL 신청 및 발급
  - public subnet에 ec2 인스턴스를 생성하여 nginx 설치후 ssl 인증 정보 설정 및 http(80)으로 들어오는 요청에 대하여 리다이렉트 설정

### 4. 일련의 과정을 이해해보려고 회원가입을 예로 들어 그려본 프로세스
![image](https://github.com/user-attachments/assets/36ccf73a-5698-4ecf-8796-70a296d31293)
