### ISSUE TITLE
[API] Admin 에서 accommodation 등록

### ISSUE THREAD

**Issue by f-lab-robert** [f-lab-edu/retry-lee#23]

**Comment by sypatrick** [comment]
1. 같은 로직 중복되지 않게 우선 user 모듈에서 Spring Security, Jwt, Jpa Auditing 수정.
    - 추후 분리작업이 필요할 경우 진행.
2. 위 작업 완료 후 api-admin 모듈에서 호텔 등록 API 진행

**Comment by sypatrick** [comment]
[Context]

숙소와 숙소의 방을 등록할 수 있어야한다.
