### ISSUE TITLE
3. 프로젝트 생성

### ISSUE THREAD

**Issue by f-lab-robert** [f-lab-edu/retry-lee#3]
**[Context]**

1. Java / SpringBoot
- Jpa (O)
- QueryDsl (X)
 
2. Vue.js (version 3)
- 로그인, 회원가입 페이지 만들예정 

3. Infra (AWS)
- ECS, github action

**Comment by f-lab-robert** [comment]
**1. 멀티 모듈의 장단점**

**2. 설계는 다음과 같이**
- api-user
   - web
      - dto, controller
   - service

- api-admin

- storage
   - entity
   - repository
   
- support
   - logging
   - utility
   
 **3. 2의 폴더구조의 장단점 & 대체제를 제안해주세요**
 - 여러 폴더 구조들을 학습해보시면 좋을 것 같습니다. ( DDD, Clean Archi, Onion Archi.... )

**Comment by sypatrick** [comment]
코멘트에 작성하면 가독성이 좋지 않을 것 같아 정리겸 위키에 작성하였습니다.
[아키텍처 정리](https://github.com/f-lab-edu/retry-lee/wiki/%EC%95%84%ED%82%A4%ED%85%8D%EC%B2%98-%EA%B5%AC%EC%A1%B0)
