### ISSUE TITLE
4. ECS 학습

### ISSUE THREAD

**Issue by f-lab-robert** [f-lab-edu/retry-lee#4]
**1. AWS**

- ECS : ECS 에 대해 간단하게 나마 학습
   - ECS 의 기본 개념 ( Task, Task definition, Service ) 에 대해 학습
   - 다이어그램 같은 것을 통해 본인이 만들고 싶은 ECS 의 형상을 그려보기
   - 개괄적으로 1 CPU, 2 Memory 의 서버 2대를 1달 동안 운영한다고 했을 때, 예상되는 비용

**Comment by sypatrick** [comment]
ECS는 AWS에서 제공하는 관리형 컨테이너 *오케스트레이션 서비스이다.

a) Task
 - ECS에서 실행되는 가장 작은 단위의 작업
 - 하나 이상의 컨테이너로 구성된다.
 - 일시적이며, 완료되면 종료된다.

b) Task Definition
 - Tesk를 어떻게 실행할지 정의하는 청사진이다.
 - 컨테이너 이미지, CPU/메모리 요구사항, 포트매핑, 환경변수 등을 지정한다.

c) Service
 - Task를 장기적으로 실행하고 관리하는 구성이다.
 - 지정된 수의 Task를 계속 실행하도록 보장한다.
 - 로드 밸런서와 통합하여 트래픽을 분산할 수 있다.
***
오케스트레이션 서비스란?
 - 다수의 컨테이너화된 애플리케이션을 배포, 관리, 확장, 네트워킹 그리고 모니터링등을 자동화하는 시스템을 의미한다.
 대표적으로 Kubernetes, AWS의 ECS 가 있다.

잘 이해가 가지않아 알기쉽게 학교 급식에 비유해보면 다음과 같이 생각할 수 있을 것 같다.
- 컨테이너 -> 급식판
  - 급식판에 있는 각각의 음식은 컨테이너 안에 있는 애플리케이션이나 서비스라고 생각
- 확장 -> 급식판이 모자르지 않도록 준비
  - 사용자가 많아 질때 더 많은 컨테이너를 자동으로 추가하여 트래픽 처리
- 모니터링 관리 -> 배식 담당 교사
  - 잘 먹고 있는지, 급식판 잘 배분되고 있는지 확인 하는 것 처럼 컨테이너가 잘 작동하고 있는지 확인.

**Comment by sypatrick** [comment]
![image](https://github.com/user-attachments/assets/2ac8eaee-cf5b-4c07-a085-12303da24ecc)

**Comment by sypatrick** [comment]
![image](https://github.com/user-attachments/assets/59ee0cba-7b29-4a45-b1f7-7ddc4f7069e8)
## 용어 정리
***
### VPC
- 정의: AWS VPC는 AWS 클라우드 내에 격리된 가상 네트워크를 생성할 수 있는 서비스. VPC를 사용하면 AWS 리소스(EC2 인스턴스, RDS 데이터베이스 등)를 논리적으로 분리된 네트워크 내에서 운영할 수 있다.

### public subnet
- 정의: 퍼블릭 서브넷은 인터넷과 직접 연결될 수 있는 서브넷. 일반적으로 퍼블릭 서브넷은 인터넷과 연결된 리소스(예: 웹 서버, 로드 밸런서)를 배치하는 데 사용된다.

### private subnet
- 정의: 프라이빗 서브넷은 인터넷과 직접 연결되지 않는 서브넷. 프라이빗 서브넷의 리소스는 외부 인터넷과의 직접적인 통신 없이 내부 네트워크 및 특정 서비스와만 통신할 수 있다.

***
## 크게 봤을 때 해야 할 3가지

**_1. ECR 저장소 설정
2. ECS 생성 및 설정(Task Definition, Service)
3. Github Action workflow 작성_**

### Task Definition 내용
 - 이름, docker image(ECR), 포트, 프로토콜 등 입력
 - 환경(EC2 or Fargate), 운영체제, CPU, 메모리, 컨테이너 크기, IAM Role 설정
 - Json 으로 편집 가능

### Service 내용
 - 시작 유형 선택(EC2 or Fargate)
 - 작업 정의 (작성한 Task Definition)
 - 클러스터, 서비스 이름, 작업 개수등 설정

### Github Action workflow
 - JDK 설정
 - 프로젝트 빌드 ( Gradle )
 - 필요시 application.yml 추가
 - ECR 로그인
 - Docker image 빌드
 - image를 ECR 에 push
 - ECS에 새로운 이미지 배포 ( task definition , service, region 등 지정)

**Comment by sypatrick** [comment]
### ECS 예상 비용

- Task 수 : 3개(user, admin, FrontEnd) * (730시간 (1달 기준) / 24시간 ) = 한달에 약 92 개
- 92 * 1vCPU * 24시간 * 0.04656(서울 리전 시간당 USD) USD = 약 102.80 불
- 92 * 2GB * 24시간 * 0.00511(서울 리전 시간당 USD) USD = 약 22.56불
- 합계 : 102.80 + 22.56 = 125.36
- 서버 2대 사용시 약 250.72 불의 비용 지불 예상
